adminUser:
  password: vault:cosmin-dwjw/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jx-bot@gmx.ch
  token: vault:cosmin-dwjw/pipelineUser:token
  username: ccojocar-bot
prow:
  hmacToken: vault:cosmin-dwjw/prow:hmacToken
